language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew build"

notifications:
  slack: asearchworkspace:4V3B2DvvLytHrgDaeSNGLxWY